version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: 
          working_directory: src
          command: npm install
      - run: 
          working_directory: src
          command: npm run production
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          aws configure set aws_access_key_id "${AWS_ACCESS_KEY}"
          aws configure set aws_secret_access_key "${AWS_SECRET_KEY}"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
