version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2.11-node-browsers
    working_directory: src/
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
  deploy:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "69:43:63:c3:51:02:3c:3a:86:ed:65:6e:18:7f:11:91"
      - run:
          name: Clone or Pull lalavel-app repository to EC2
          command: |
            ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/ && git clone https://github.com/task-01/lalavel-app.git . || (cd lalavel-app && git pull origin main)'

