version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2.11-node-browsers
    working_directory: /app
    steps:
      - checkout
      - run: mkdir -p /app
      - run: sudo composer self-update --stable
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - checkout
