version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: circleci/php:7.2.11-node-browsers
    working_directory: /src
    steps:
      - checkout
      - run: sudo composer self-update --stable
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - checkout
