version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2.11-node-browsers
    working_directory: /src
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
  deploy:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "your-ssh-fingerprint"
      - run:
          name: Clone lalavel-app repository
          command: |
            git clone https://github.com/task-01/lalavel-app.git src/

