version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: /app  # 作業ディレクトリをプロジェクトのルートに設定
    steps:
      - checkout
      - setup_remote_docker:  # Dockerサービスを有効にする
          docker_layer_caching: true
      - run:
          name: Start Docker Compose
          command: docker-compose up -d
      - run:
          name: Composer Install
          command: docker-compose exec php composer install
      - run: npm install
      - run: npm run production
      - run: docker build -t myapp .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
